/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_aside_host_aside_create_parameter_0$schema = z.object({
  'parentSessionId': z.string(),
})
const _deepseek_ai_dsh_aside_host_aside_create_result$schema = z.object({
  'sessionId': z.string(),
  'agentPreset': z.string(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-aside-host',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-aside-host#aside/create',
      service: 'aside',
      namespace: 'aside',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-aside-host/types#AsideCreateRequest',
            schema: _deepseek_ai_dsh_aside_host_aside_create_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-aside-host/types#AsideCreateResult',
        schema: _deepseek_ai_dsh_aside_host_aside_create_result$schema,
      },
      sourceLocation: {"file":"packages/aside/aside-host/src/index.ts","line":96,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
