/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AsideCreateRequest, AsideCreateResult } from '@deepseek-ai/dsh-aside-host/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6173696465 {
    create: (request: AsideCreateRequest) => Promise<RemoteResult<AsideCreateResult>>
  }
  interface TypertRemoteMap {
    'aside/create': (request: AsideCreateRequest) => Promise<RemoteResult<AsideCreateResult>>
  }
  interface TypertRemoteNamespaceMap {
    'aside': TypertRemoteNamespace$6173696465
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
